spring:
  profiles:
    active:
      -dev
---
spring:
  application:
    name: config-client
  profiles: dev
server:
  port: 8766
username: chuwei223344
---
spring:
  application:
    name: config-client
  profiles: beta
server:
  port: 9999
